package com.siddhesh.pixelpdf.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val md3_primary_light = Color(0xFF6750A4)
val md3_on_primary_light = Color(0xFFFFFFFF)
val md3_primary_container_light = Color(0xFFEADDFF)
val md3_on_primary_container_light = Color(0xFF21005D)
val md3_secondary_light = Color(0xFF625B71)
val md3_on_secondary_light = Color(0xFFFFFFFF)
val md3_secondary_container_light = Color(0xFFE8DEF8)
val md3_on_secondary_container_light = Color(0xFF1D192B)
val md3_tertiary_light = Color(0xFF7D5260)
val md3_on_tertiary_light = Color(0xFFFFFFFF)
val md3_tertiary_container_light = Color(0xFFFFD8E4)
val md3_on_tertiary_container_light = Color(0xFF31111D)
val md3_error_light = Color(0xFFB3261E)
val md3_on_error_light = Color(0xFFFFFFFF)
val md3_error_container_light = Color(0xFFF9DEDC)
val md3_on_error_container_light = Color(0xFF410E0B)
val md3_surface_light = Color(0xFFFEF7FF)
val md3_on_surface_light = Color(0xFF1D1B20)
val md3_surface_variant_light = Color(0xFFE7E0EC)
val md3_on_surface_variant_light = Color(0xFF49454F)
val md3_surface_container_lowest_light = Color(0xFFFFFFFF)
val md3_surface_container_low_light = Color(0xFFF7F2FA)
val md3_surface_container_light = Color(0xFFF3EDF7)
val md3_surface_container_high_light = Color(0xFFECE6F0)
val md3_surface_container_highest_light = Color(0xFFE6E0E9)
val md3_outline_light = Color(0xFF79747E)
val md3_outline_variant_light = Color(0xFFCAC4D0)

// Dark Theme
val md3_primary_dark = Color(0xFFD0BCFF)
val md3_on_primary_dark = Color(0xFF381E72)
val md3_primary_container_dark = Color(0xFF4F378B)
val md3_on_primary_container_dark = Color(0xFFEADDFF)
val md3_secondary_dark = Color(0xFFCCC2DC)
val md3_on_secondary_dark = Color(0xFF332D41)
val md3_secondary_container_dark = Color(0xFF4A4458)
val md3_on_secondary_container_dark = Color(0xFFE8DEF8)
val md3_tertiary_dark = Color(0xFFEFB8C8)
val md3_on_tertiary_dark = Color(0xFF492532)
val md3_tertiary_container_dark = Color(0xFF633B48)
val md3_on_tertiary_container_dark = Color(0xFFFFD8E4)
val md3_error_dark = Color(0xFFF2B8B5)
val md3_on_error_dark = Color(0xFF601410)
val md3_error_container_dark = Color(0xFF8C1D18)
val md3_on_error_container_dark = Color(0xFFF9DEDC)
val md3_surface_dark = Color(0xFF141218)
val md3_on_surface_dark = Color(0xFFE6E0E9)
val md3_surface_variant_dark = Color(0xFF49454F)
val md3_on_surface_variant_dark = Color(0xFFCAC4D0)
val md3_surface_container_lowest_dark = Color(0xFF0F0D13)
val md3_surface_container_low_dark = Color(0xFF1D1B20)
val md3_surface_container_dark = Color(0xFF211F26)
val md3_surface_container_high_dark = Color(0xFF2B2930)
val md3_surface_container_highest_dark = Color(0xFF36343B)
val md3_outline_dark = Color(0xFF938F99)
val md3_outline_variant_dark = Color(0xFF49454F)

// Sepia Theme
val md3_primary_sepia = Color(0xFF8B6914)
val md3_on_primary_sepia = Color(0xFFFFFFFF)
val md3_primary_container_sepia = Color(0xFFF4E1B0)
val md3_on_primary_container_sepia = Color(0xFF2B1F00)
val md3_surface_sepia = Color(0xFFF4EFE0)
val md3_on_surface_sepia = Color(0xFF3B3226)
val md3_surface_variant_sepia = Color(0xFFE7DFC9)
val md3_on_surface_variant_sepia = Color(0xFF4A4639)
val md3_surface_container_sepia = Color(0xFFEAE5D6)
val md3_surface_container_high_sepia = Color(0xFFE4DFD0)
val md3_surface_container_highest_sepia = Color(0xFFDED9CA)
